FROM mhart/alpine-node:13 AS builder
WORKDIR /app
COPY . .
WORKDIR /app/packages
RUN yarn install
WORKDIR /app/packages/app
RUN yarn install
RUN yarn run build

FROM mhart/alpine-node:13
RUN yarn global add serve
WORKDIR /app/packages/app
COPY --from=builder /app/packages/app/build .
CMD ["serve", "-p", "80", "-s", "."]